title: Ayshia
logo: /assets/img/headshot.jpg
description:	Marketing professional with 10+ years of experience in fashion retail and 5 years of management experience specializing in site optimization, eCommerce growth, and consumer behavior research proven to drive measurable impact for lifestyle and fashion brands. 
Hands-on experience in Python, SQL, and analytics tools to extract, interpret, and visualize data that informs product roadmaps, drive strategy, enhances digital experiences, supports cross-functional product roadmaps and pushes measurable business outcomes.
Experienced in connecting creativity and data to translate consumer insights into actionable stories that inspire teams to build products customers genuinely trust and enjoy. 

show_downloads: true
theme: minima-theme
